#ifndef FCP_CONFIDENTIALCOMPUTE_CRYPTO_TEST_UTIL_H_
#define FCP_CONFIDENTIALCOMPUTE_CRYPTO_TEST_UTIL_H_

#include <string>
#include <utility>

#include "absl/strings/string_view.h"

namespace fcp::confidential_compute {

// Generates a new public/private HPKE key pair like would be generated by the
// KMS. The public key is encoded as a CWT and the private key is encoded as a
// COSE_Key.
std::pair<std::string, std::string> GenerateHpkeKeyPair(
    absl::string_view key_id);

}  // namespace fcp::confidential_compute

#endif  // FCP_CONFIDENTIALCOMPUTE_CRYPTO_TEST_UTIL_H_
